apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: semics
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app.v10
  name: app.v10
  namespace: semics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app.v10
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app.v10
    spec:
      containers:
      - image: acrsharedcommon64963.azurecr.io/app.v10
        name: app.v10
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app.v10
  name: app.v10
  namespace: semics
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app.v10
  type: ClusterIP
status:
  loadBalancer: {}
